config/routes.rb
UnPoliticsApp::Application.routes.draw do
  
  root "states#index"
  resources :states
  resources :politicians, only: [:index, :show, :timeline] do
    resources :written_statements
  end   

  get "politicians/:id/timeline", to: "politicians#timeline", as: "politician_timeline"
  post "politicians/:politician_id/written_statements/new", to: "written_statements#create"

 	get "written_statements/create"
  devise_for :users

end

  

app/models/politician.rb
class Politician < ActiveRecord::Base
	belongs_to :state
	has_many :written_statements
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :politicians
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/written_statement.rb
class WrittenStatement < ActiveRecord::Base
	belongs_to :politician

	validates :statements, :body, :path, :date, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show, :edit, :update, :destroy]

  # GET /politicians
  # GET /politicians.json
  def index
    @politicians = Politician.all
  end

  # GET /politicians/1
  # GET /politicians/1.json
  def show
    @politician = Politician.find(params[:id])
    # if @politician.district != nil
  end

  # GET /politicians/new
  def new
    @politician = Politician.new
  end

  def timeline
    @politician = Politician.find(params[:id])
    @written_statements = @politician.written_statements.order('date ASC')
  end


  # GET /politicians/1/edit
  def edit
  end

  # POST /politicians
  # POST /politicians.json
  # def create
  #   @politician = Politician.new(politician_params)

  #   respond_to do |format|
  #     if @politician.save
  #       format.html { redirect_to @politician, notice: 'Politician was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @politician }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @politician.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /politicians/1
  # PATCH/PUT /politicians/1.json
  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to @politician, notice: 'Politician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
    @politician.destroy
    respond_to do |format|
      format.html { redirect_to politicians_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politician_params
      params.require(:politician).permit(:name, :image, :position1, :position2, :state, :district, :party, :sworn_in, :person_defeated, :votes_w_party, :votes_vs_party, :abstains)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: :show

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render action: 'show', status: :created, location: @state }
      else
        format.html { render action: 'new' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:state, :district)
    end
end

app/controllers/written_statements_controller.rb
class WrittenStatementsController < ApplicationController
  before_action :set_written_statement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :add_written_statement, only: [:new, :create]

  def index
    @written_statements = WrittenStatement.all
  end

  def show
    @written_statement = WrittenStatement.find(params[:id], :order => 'DATE(date)')
  end

  def new
    @politician = Politician.find(params[:politician_id])
    @written_statement = @politician.written_statements.new
  end

  def create
    if user_signed_in?
      safe_written_statement = params.require(:written_statement).permit(:statements, :body, :path).merge(politician_id: params[:politician_id])
      # @written_statement = current_user.written_statements.create safe_written_statement
      # redirect_to politician_timeline_path(@politician.id)
    end
    @politician = Politician.find(params[:politician_id])
    @written_statement = @politician.written_statements.new(written_statement_params)
    if @written_statement.save
      redirect_to politician_timeline_path(@politician.id)
    else
      render 'new'
    end
    
  end

  private
    def set_written_statement
      @written_statement = WrittenStatement.find(params[:id])
    end

    def written_statement_params
      params.require(:written_statement).permit(:statements, :body, :path, :politician_id, :date)
    end

    def add_written_statement
    @written_statement = WrittenStatement.create
      rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Invalid statement"
    redirect_to new_politician_written_statement_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
	def pol_data


	end

end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/written_statements_helper.rb
module WrittenStatementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnPoliticsApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


</body>
</html>

app/views/politicians/_form.html.erb
<%= form_for(@politician) do |f| %>
  <% if @politician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@politician.errors.count, "error") %> prohibited this politician from being saved:</h2>

      <ul>
      <% @politician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :position1 %><br>
    <%= f.text_field :position1 %>
  </div>
  <div class="field">
    <%= f.label :position2 %><br>
    <%= f.text_field :position2 %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="field">
    <%= f.label :sworn_in %><br>
    <%= f.number_field :sworn_in %>
  </div>
  <div class="field">
    <%= f.label :person_defeated %><br>
    <%= f.text_field :person_defeated %>
  </div>
  <div class="field">
    <%= f.label :votes_w_party %><br>
    <%= f.text_field :votes_w_party %>
  </div>
  <div class="field">
    <%= f.label :votes_vs_party %><br>
    <%= f.text_field :votes_vs_party %>
  </div>
  <div class="field">
    <%= f.label :abstains %><br>
    <%= f.text_field :abstains %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politicians/edit.html.erb
<h1>Editing politician</h1>

<%= render 'form' %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', politicians_path %>

app/views/politicians/index.html.erb
<h1>Elected Officials in <%= "#{@state.state}" %></h1>

<p>Here is a listing of all of the elected officials in #{state}</p>


    <% @politicians.each do |politician| %>
      <%= link_to politician.name, politician_path(politician) %>
    <% end %>

app/views/politicians/new.html.erb
<h1>New politician</h1>

<%= render 'form' %>

<%= link_to 'Back', politicians_path %>

app/views/politicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @politician.name %>
</p>

<!-- <p>
  <strong>Image:</strong>
  <%= @politician.image %>
</p> -->

<p>
  <strong>Position:</strong>
  <%= @politician.position1 %>
</p>

<p>
  <% if @politician.position2 != "" %>
  <strong>Leadership Position:</strong>
  <%= @politician.position2 %>
  <% end %>
</p>

<p>
  <strong>State:</strong>
  <%= @politician.state.state %>
</p>

<p>
 <% if @politician.district %>
  <strong>District:</strong>
  <%= @politician.district %>
<% end %>
</p>

<p>
  <strong>Party:</strong>
  <%= @politician.party %>
</p>

<p>
  <strong>Sworn in:</strong>
  <%= @politician.sworn_in %>
</p>

<!-- <p>
  <strong>Person defeated:</strong>
  <%= @politician.person_defeated %>
</p> -->

<p>
  <strong>Votes with party:</strong>
  <%= @politician.votes_w_party %>
</p>

<p>
<% if @politician.votes_vs_party %>
  <strong>Votes vs party:</strong>
  <%= @politician.votes_vs_party %>
<% end %>
</p>

<p>
<% if @politician.abstains %>
  <strong>Abstains:</strong>
  <%= @politician.abstains %>
<% end %>
</p>

<br>
<br>
<br>

<%= link_to 'Timeline of Public Statements', politician_timeline_path(@politician.id) %>
<br>
<%= link_to 'Timeline of Public Statements by Issue (Coming Soon)' %>
<br>
<br>
<!-- <ink_to 'Edit', edit_politician_path(@politician) %> | -->

<%= link_to "Back to #{@politician.state.state} state profile page", state_path(@politician.state_id) %>

app/views/politicians/timeline.html.erb
<h2>  <strong><%= @politician.name %> Timeline of Public Statements</strong>
</h2>
<br>
<br>

   <% @written_statements.each do |written_statement| %>
     	<strong><%= link_to written_statement.statements, politician_written_statement_path(@politician.id, written_statement) %></strong>
     	<br>
        <br>
        <!-- insert thumbnails of statements, which link to url -->
        <br>
	<% end %>


        <!-- ability to sort by issue -->

		<br>
        <br>
        <br>
        <br>

	<p><%= link_to "Something missing? Please click here to submit any public statements for #{@politician.name} that you do not see here.", new_politician_written_statement_path(@politician.id) %></p>


<br>
        <br>
        <br>
        <br>

        <%= link_to "Back to #{@politician.name}'s profile", politician_path(@politician.id) %>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.number_field :district %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>UnPolitics</h1>
<!-- add navigation, map, daily feature, issue links -->
<br>
<h3>USA</h3>

    <% @states.each do |state| %>
        <%= link_to state.state, state_path(state) %><br>

    <% end %>

<br>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong><%= @state.state %></strong>
  
</h2>

    <% @state.politicians.each do |politician| %>
   <%= link_to politician.name, politician_path(politician) %><br>   

    <% end %>

<br>
<%= link_to 'Back', states_path %>

app/views/written_statements/_form.html.erb
<%= form_for @written_statement, url: new_politician_written_statement_path do |f| %>
  
  <%if user_signed_in? %>
  <%= yield %>
  <p>Logged in as <%= current_user.email %></p>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Login", new_user_session_path %>
  <% end %>


  <% if @written_statement.errors.any? %>
      <h2><%= pluralize(@written_statement.errors.count, "error") %> prohibited this written_statement from being saved:</h2>

      <ul>
      <% @written_statement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  <% end %>

  <div class="field">
    <%= f.label :statement %><br>
    <%= f.text_field :statements %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :path %>
  </div>
  <br>
  <div class="field">
    <%= f.label :date %>
    <%= 'YYYY-MM-DD' %><br>
    <%= f.text_field :date %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/written_statements/edit.html.erb
<h1>Editing written_statement</h1>

<%= render 'form' %>

<%= link_to 'Show', @written_statement %> |
<%= link_to 'Back', written_statements_path %>

app/views/written_statements/index.html.erb
<h1>Listing written_statements</h1>


    <% @written_statements.each do |written_statement| %>
      <tr>
        <td><%= link_to written_statement.statements %></td>
        <td><%= written_statement.path, written_statement_path(@politician_id) %></td>
        <td><%= link_to 'Show', written_statement %></td>
       
      </tr>
    <% end %>
  
<br>

app/views/written_statements/new.html.erb
<h1>Submit new public statement for <%= @politician.name %></h1>

<%= render 'form' %>
<br>
<br>
<%= link_to 'Back', politician_timeline_path(@politician.id) %>

app/views/written_statements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statement:
  <%= @written_statement.statements %></strong>
</p>

<p>
  <%= @written_statement.body %>
</p>

<p>
  Source:
  <%= link_to @written_statement.path, @written_statement.path, :target => '_blank'  %>
</p>

<p>
	Date: <%= @written_statement.date %>
</p>
<br>
<br>
<br>

<%= link_to 'Back', politician_timeline_path(@written_statement.politician_id) %>